name: build-ubuntu

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: setup
      run: |
        sudo apt update
        sudo apt -y install libopencv-dev libglfw3 libglfw3-dev libxkbcommon-dev libxinerama-dev libxcursor-dev libxi-dev doxygen graphviz

    - name: Configure Ubuntu
      run: cmake -B ${{github.workspace}}/build/gcc-debug -S . -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
    - name: Build Ubuntu
      run: cmake --build ${{github.workspace}}/build/gcc-debug --config ${{ matrix.configuration }} -- -j 10
    - name: Test Ubuntu
      run: |
        cd ${{github.workspace}}/build/gcc-debug
        ctest -C Debug

