name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-ubuntu:
    uses: ./.github/workflows/build-ubuntu.yml

  build-windows:
    uses: ./.github/workflows/build-windows.yml

  generate-docs:
    permissions:
      id-token: write
      pages: write
    uses: ./.github/workflows/generate-docs.yml
    if: github.ref == 'refs/heads/main'
    needs:
      - build-ubuntu
      - build-windows
